import React from 'react';
import { motion } from 'framer-motion';

const HeroSection = ({ onStartQuiz }) => {
  return (
    <div className="relative min-h-screen flex items-center justify-center px-4">
      {/* Animated background elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-10 -right-10 w-40 h-40 bg-blue-300 rounded-full opacity-20 animate-bounce-gentle"></div>
        <div className="absolute top-1/4 -left-10 w-32 h-32 bg-indigo-300 rounded-full opacity-20 animate-bounce-gentle" style={{ animationDelay: '1s' }}></div>
        <div className="absolute bottom-1/4 right-1/4 w-24 h-24 bg-purple-300 rounded-full opacity-20 animate-bounce-gentle" style={{ animationDelay: '2s' }}></div>
      </div>

      <div className="relative z-10 text-center max-w-4xl mx-auto">
        {/* Main heading */}
        <motion.h1 
          className="text-5xl md:text-6xl font-bold text-gray-800 mb-6"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
            Quiz
          </span>
          <span className="text-gray-800">Master</span>
        </motion.h1>

        {/* Subtitle */}
        <motion.p 
          className="text-xl md:text-2xl text-gray-600 mb-8 leading-relaxed"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          Test your knowledge with AI-powered quizzes.<br />
          <span className="text-blue-600 font-semibold">Learn, Challenge, Excel.</span>
        </motion.p>

        {/* Features list */}
        <motion.div 
          className="grid md:grid-cols-3 gap-6 mb-10"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          <div className="bg-white/20 backdrop-blur-sm rounded-lg p-6 border border-white/30">
            <div className="text-blue-500 text-3xl mb-3">🎯</div>
            <h3 className="font-semibold text-gray-800 mb-2">Custom Topics</h3>
            <p className="text-gray-600 text-sm">Quiz on any topic you choose</p>
          </div>
          
          <div className="bg-white/20 backdrop-blur-sm rounded-lg p-6 border border-white/30">
            <div className="text-green-500 text-3xl mb-3">⚡</div>
            <h3 className="font-semibold text-gray-800 mb-2">AI-Powered</h3>
            <p className="text-gray-600 text-sm">Questions generated by Google Gemini</p>
          </div>
          
          <div className="bg-white/20 backdrop-blur-sm rounded-lg p-6 border border-white/30">
            <div className="text-purple-500 text-3xl mb-3">📊</div>
            <h3 className="font-semibold text-gray-800 mb-2">Instant Results</h3>
            <p className="text-gray-600 text-sm">Detailed explanations and scores</p>
          </div>
        </motion.div>

        {/* CTA button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.6 }}
        >
          <button
            onClick={onStartQuiz}
            className="
              bg-gradient-to-r from-blue-600 to-indigo-600 
              hover:from-blue-700 hover:to-indigo-700
              text-white font-bold py-4 px-8 rounded-full
              text-lg transition-all duration-300
              transform hover:scale-105 hover:shadow-lg
              focus:outline-none focus:ring-4 focus:ring-blue-300
              inline-flex items-center space-x-2
            "
          >
            <span>Start Your Quiz</span>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </button>
        </motion.div>

        {/* Stats */}
        <motion.div 
          className="flex justify-center space-x-8 mt-12 text-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.8 }}
        >
          <div>
            <div className="text-2xl font-bold text-blue-600">∞</div>
            <div className="text-sm text-gray-600">Topics Available</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-green-600">20</div>
            <div className="text-sm text-gray-600">Max Questions</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-purple-600">3</div>
            <div className="text-sm text-gray-600">Difficulty Levels</div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default HeroSection;
